
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DomainModelProject
{

using System;
    using System.Collections.Generic;
    
public partial class App
{

    public App()
    {

        this.AspNetUsers = new HashSet<AspNetUser>();

    }


    public int AppID { get; set; }

    public string AppName { get; set; }

    public string GoogleIdentity { get; set; }

    public string IOSIdentity { get; set; }



    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }

}

}
