//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long ID { get; set; }
        public Nullable<int> AuditType { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public Nullable<long> AuditEntity { get; set; }
        public string AuditEntityDescription { get; set; }
        public string TableName { get; set; }
    }
}
