//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignEventHistory
    {
        public long EventId { get; set; }
        public Nullable<int> EventStatusId { get; set; }
        public Nullable<long> CampaignID { get; set; }
        public Nullable<System.DateTime> EventDateTime { get; set; }
        public Nullable<long> CouponId { get; set; }
        public Nullable<long> SQID { get; set; }
        public Nullable<int> PQID { get; set; }
    
        public virtual AdCampaign AdCampaign { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual EventStatus EventStatus { get; set; }
        public virtual ProfileQuestion ProfileQuestion { get; set; }
        public virtual SurveyQuestion SurveyQuestion { get; set; }
    }
}
