//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.AdCampaignTargetLocations = new HashSet<AdCampaignTargetLocation>();
            this.ProfileQuestionGroups = new HashSet<ProfileQuestionGroup>();
            this.Products = new HashSet<Product>();
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
            this.SurveyQuestionTargetLocations = new HashSet<SurveyQuestionTargetLocation>();
            this.Taxes = new HashSet<Tax>();
            this.ProfileQuestionTargetLocations = new HashSet<ProfileQuestionTargetLocation>();
            this.Cities = new HashSet<City>();
            this.Companies = new HashSet<Company>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
    
        public virtual ICollection<AdCampaignTargetLocation> AdCampaignTargetLocations { get; set; }
        public virtual ICollection<ProfileQuestionGroup> ProfileQuestionGroups { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual ICollection<SurveyQuestionTargetLocation> SurveyQuestionTargetLocations { get; set; }
        public virtual ICollection<Tax> Taxes { get; set; }
        public virtual ICollection<ProfileQuestionTargetLocation> ProfileQuestionTargetLocations { get; set; }
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
    }
}
