//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCategory1
    {
        public CouponCategory1()
        {
            this.CampaignCategories = new HashSet<CampaignCategory>();
            this.CouponCategories = new HashSet<CouponCategories>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<CampaignCategory> CampaignCategories { get; set; }
        public virtual ICollection<CouponCategories> CouponCategories { get; set; }
    }
}
