//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomUrl
    {
        public long UrlId { get; set; }
        public string ShortUrl { get; set; }
        public string ActualUrl { get; set; }
        public Nullable<long> UserId { get; set; }
    }
}
