//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamImage
    {
        public long ImageId { get; set; }
        public string ImageTitle { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<int> ImageCategory { get; set; }
        public string CreatedDateTime { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
