
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DomainModelProject
{

using System;
    using System.Collections.Generic;
    
public partial class DiscountVoucher
{

    public long DiscountVoucherId { get; set; }

    public string VoucherCode { get; set; }

    public Nullable<System.DateTime> ValidFromDate { get; set; }

    public Nullable<System.DateTime> ValidUptoDate { get; set; }

    public Nullable<int> ProductID { get; set; }

    public double DiscountRate { get; set; }

    public Nullable<System.DateTime> ConsumedDate { get; set; }

    public bool IsEnabled { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string VoucherName { get; set; }

    public string CouponCode { get; set; }

    public Nullable<int> CouponUseType { get; set; }



    public virtual Product Product { get; set; }

}

}
