
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DomainModelProject
{

using System;
    using System.Collections.Generic;
    
public partial class Education
{

    public Education()
    {

        this.AdCampaignTargetCriterias = new HashSet<AdCampaignTargetCriteria>();

        this.AspNetUsers = new HashSet<AspNetUser>();

        this.SurveyQuestionTargetCriterias = new HashSet<SurveyQuestionTargetCriteria>();

        this.ProfileQuestionTargetCriterias = new HashSet<ProfileQuestionTargetCriteria>();

    }


    public long EducationId { get; set; }

    public string Title { get; set; }

    public Nullable<int> Status { get; set; }



    public virtual ICollection<AdCampaignTargetCriteria> AdCampaignTargetCriterias { get; set; }

    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }

    public virtual ICollection<SurveyQuestionTargetCriteria> SurveyQuestionTargetCriterias { get; set; }

    public virtual ICollection<ProfileQuestionTargetCriteria> ProfileQuestionTargetCriterias { get; set; }

}

}
