//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventStatus
    {
        public EventStatus()
        {
            this.CampaignEventHistories = new HashSet<CampaignEventHistory>();
        }
    
        public int EventStatusId { get; set; }
        public string EventName { get; set; }
    
        public virtual ICollection<CampaignEventHistory> CampaignEventHistories { get; set; }
    }
}
