//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameExerciseCategory
    {
        public long GameId { get; set; }
        public int ExerciseCategoryId { get; set; }
        public Nullable<int> CategoryContribution { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual GameExerciseCategoryList GameExerciseCategoryList { get; set; }
    }
}
