//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameExerciseCategoryList
    {
        public GameExerciseCategoryList()
        {
            this.GameExerciseCategories = new HashSet<GameExerciseCategory>();
        }
    
        public int ExerciseCategoryId { get; set; }
        public string ExerciseCategoryName { get; set; }
    
        public virtual ICollection<GameExerciseCategory> GameExerciseCategories { get; set; }
    }
}
