//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public long InvoiceDetailId { get; set; }
        public long InvoiceId { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> ItemTax { get; set; }
        public double ItemAmount { get; set; }
        public double ItemGrossAmount { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<long> CampaignId { get; set; }
        public Nullable<long> SQId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual AdCampaign AdCampaign { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
        public virtual SurveyQuestion SurveyQuestion { get; set; }
    }
}
