//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public long InvoiceId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime InvoiceDueDate { get; set; }
        public Nullable<double> TaxPercentage { get; set; }
        public double Total { get; set; }
        public double NetTotal { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string CreditCardRef { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Company Company { get; set; }
    }
}
