
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DomainModelProject
{

using System;
    using System.Collections.Generic;
    
public partial class Language
{

    public Language()
    {

        this.AdCampaigns = new HashSet<AdCampaign>();

        this.AdCampaignTargetCriterias = new HashSet<AdCampaignTargetCriteria>();

        this.AspNetUsers = new HashSet<AspNetUser>();

        this.Coupons = new HashSet<Coupon>();

        this.SurveyQuestions = new HashSet<SurveyQuestion>();

        this.SurveyQuestionTargetCriterias = new HashSet<SurveyQuestionTargetCriteria>();

        this.ProfileQuestionTargetCriterias = new HashSet<ProfileQuestionTargetCriteria>();

    }


    public int LanguageID { get; set; }

    public string LanguageName { get; set; }

    public string NativeName { get; set; }



    public virtual ICollection<AdCampaign> AdCampaigns { get; set; }

    public virtual ICollection<AdCampaignTargetCriteria> AdCampaignTargetCriterias { get; set; }

    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }

    public virtual ICollection<Coupon> Coupons { get; set; }

    public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }

    public virtual ICollection<SurveyQuestionTargetCriteria> SurveyQuestionTargetCriterias { get; set; }

    public virtual ICollection<ProfileQuestionTargetCriteria> ProfileQuestionTargetCriterias { get; set; }

}

}
