//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMDDevEntities : DbContext
    {
        public SMDDevEntities()
            : base("name=SMDDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AdCampaign> AdCampaigns { get; set; }
        public virtual DbSet<AdCampaignResponse> AdCampaignResponses { get; set; }
        public virtual DbSet<AdCampaignTargetCriteria> AdCampaignTargetCriterias { get; set; }
        public virtual DbSet<AdCampaignTargetLocation> AdCampaignTargetLocations { get; set; }
        public virtual DbSet<App> Apps { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<BranchCategory> BranchCategories { get; set; }
        public virtual DbSet<CampaignCategory> CampaignCategories { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryLog> CategoryLogs { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CompaniesAspNetUser> CompaniesAspNetUsers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyBranch> CompanyBranches { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<CouponCode> CouponCodes { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CustomUrl> CustomUrls { get; set; }
        public virtual DbSet<DiscountVoucher> DiscountVouchers { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<EmailQueue> EmailQueues { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProfileQuestion> ProfileQuestions { get; set; }
        public virtual DbSet<ProfileQuestionAnswer> ProfileQuestionAnswers { get; set; }
        public virtual DbSet<ProfileQuestionGroup> ProfileQuestionGroups { get; set; }
        public virtual DbSet<ProfileQuestionUserAnswer> ProfileQuestionUserAnswers { get; set; }
        public virtual DbSet<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual DbSet<SurveyQuestionResponse> SurveyQuestionResponses { get; set; }
        public virtual DbSet<SurveyQuestionTargetCriteria> SurveyQuestionTargetCriterias { get; set; }
        public virtual DbSet<SurveyQuestionTargetLocation> SurveyQuestionTargetLocations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemMail> SystemMails { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
        public virtual DbSet<UserFavouriteCoupon> UserFavouriteCoupons { get; set; }
        public virtual DbSet<CouponCategories> CouponCategories { get; set; }
        public virtual DbSet<CouponCategory1> CouponCategories1 { get; set; }
    }
}
