//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileQuestion
    {
        public ProfileQuestion()
        {
            this.AdCampaignTargetCriterias = new HashSet<AdCampaignTargetCriteria>();
            this.ProfileQuestionAnswers = new HashSet<ProfileQuestionAnswer>();
            this.ProfileQuestionUserAnswers = new HashSet<ProfileQuestionUserAnswer>();
            this.SurveyQuestionTargetCriterias = new HashSet<SurveyQuestionTargetCriteria>();
        }
    
        public int PQID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> ProfileGroupID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Type { get; set; }
        public string Question { get; set; }
        public Nullable<int> RefreshTime { get; set; }
        public Nullable<int> SkippedCount { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> HasLinkedQuestions { get; set; }
        public Nullable<int> PenalityForNotAnswering { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> AnswerNeeded { get; set; }
        public Nullable<int> AsnswerCount { get; set; }
    
        public virtual ICollection<AdCampaignTargetCriteria> AdCampaignTargetCriterias { get; set; }
        public virtual ICollection<ProfileQuestionAnswer> ProfileQuestionAnswers { get; set; }
        public virtual ProfileQuestionGroup ProfileQuestionGroup { get; set; }
        public virtual ICollection<ProfileQuestionUserAnswer> ProfileQuestionUserAnswers { get; set; }
        public virtual ICollection<SurveyQuestionTargetCriteria> SurveyQuestionTargetCriterias { get; set; }
        public virtual Company Company { get; set; }
    }
}
