//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileQuestionUserAnswer
    {
        public long PQUAnswerID { get; set; }
        public int PQID { get; set; }
        public string UserID { get; set; }
        public System.DateTime AnswerDateTime { get; set; }
        public int PQAnswerID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ResponseType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ProfileQuestion ProfileQuestion { get; set; }
        public virtual ProfileQuestionAnswer ProfileQuestionAnswer { get; set; }
        public virtual Company Company { get; set; }
    }
}
