
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DomainModelProject
{

using System;
    using System.Collections.Generic;
    
public partial class ProfileQuestionGroup
{

    public ProfileQuestionGroup()
    {

        this.ProfileQuestions = new HashSet<ProfileQuestion>();

    }


    public int ProfileGroupID { get; set; }

    public string ProfileGroupName { get; set; }

    public string ImagePath { get; set; }

    public Nullable<int> LangaugeID { get; set; }

    public Nullable<int> CountryID { get; set; }



    public virtual Country Country { get; set; }

    public virtual ICollection<ProfileQuestion> ProfileQuestions { get; set; }

}

}
