
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DomainModelProject
{

using System;
    using System.Collections.Generic;
    
public partial class Section
{

    public Section()
    {

        this.Phrases = new HashSet<Phrase>();

    }


    public int SectionId { get; set; }

    public string SectionName { get; set; }

    public int SecOrder { get; set; }



    public virtual ICollection<Phrase> Phrases { get; set; }

}

}
