//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedSurveyQuestion
    {
        public SharedSurveyQuestion()
        {
            this.SharedSurveyQuestionResponses = new HashSet<SharedSurveyQuestionResponse>();
            this.SurveySharingGroupShares = new HashSet<SurveySharingGroupShare>();
        }
    
        public long SSQID { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string SurveyTitle { get; set; }
        public string LeftPicturePath { get; set; }
        public string RightPicturePath { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> SharingGroupId { get; set; }
    
        public virtual ICollection<SharedSurveyQuestionResponse> SharedSurveyQuestionResponses { get; set; }
        public virtual ICollection<SurveySharingGroupShare> SurveySharingGroupShares { get; set; }
        public virtual SurveySharingGroup SurveySharingGroup { get; set; }
    }
}
