//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedSurveyQuestionResponse
    {
        public long SSQResponseId { get; set; }
        public Nullable<long> SSQID { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
        public Nullable<int> UserSelection { get; set; }
    
        public virtual SharedSurveyQuestion SharedSurveyQuestion { get; set; }
    }
}
