//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySharingGroupShare
    {
        public SurveySharingGroupShare()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public long SurveyQuestionShareId { get; set; }
        public Nullable<long> SharingGroupId { get; set; }
        public string UserId { get; set; }
        public Nullable<long> SharingGroupMemberId { get; set; }
        public Nullable<System.DateTime> SharingDate { get; set; }
        public Nullable<long> SSQID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
        public Nullable<int> UserSelection { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual SharedSurveyQuestion SharedSurveyQuestion { get; set; }
        public virtual SurveySharingGroupMember SurveySharingGroupMember { get; set; }
    }
}
