//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMail
    {
        public int MailID { get; set; }
        public string Title { get; set; }
        public string FromName { get; set; }
        public string fromEmail { get; set; }
        public string Subject { get; set; }
        public string body { get; set; }
        public Nullable<int> EmailTarget { get; set; }
    }
}
