//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int TaxId { get; set; }
        public string TaxName { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public int CountryId { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
