//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransactionLogs = new HashSet<TransactionLog>();
        }
    
        public long TxID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> DebitCredit { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<double> DebitAmount { get; set; }
        public Nullable<long> AccountID { get; set; }
        public Nullable<double> TaxPerc { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public Nullable<long> AdCampaignID { get; set; }
        public Nullable<long> SQID { get; set; }
        public Nullable<bool> isProcessed { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> CurrencyRateID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<double> AccountBalance { get; set; }
        public Nullable<long> CouponId { get; set; }
        public Nullable<int> PQID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
    }
}
