
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DomainModelProject
{

using System;
    using System.Collections.Generic;
    
public partial class UserCouponView
{

    public long UserCouponViewId { get; set; }

    public Nullable<long> CouponId { get; set; }

    public string UserId { get; set; }

    public Nullable<System.DateTime> ViewDateTime { get; set; }

    public string userLocationLAT { get; set; }

    public string userLocationLONG { get; set; }

}

}
