
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DomainModelProject
{

using System;
    using System.Collections.Generic;
    
public partial class vw_ReferringCompanies
{

    public string FullName { get; set; }

    public string Email { get; set; }

    public string CompanyName { get; set; }

    public Nullable<int> vcount { get; set; }

    public Nullable<int> scount { get; set; }

    public Nullable<int> pcount { get; set; }

    public Nullable<int> ReferringCompanyID { get; set; }

}

}
