//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMD.Models.DomainModels
{
    using SMD.Models.IdentityModels;
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersNotificationToken
    {
        public long NotificationTokenId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ClientType { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual User AspNetUser { get; set; }
    }
}
