//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBranch
    {
        public CompanyBranch()
        {
            this.Coupons = new HashSet<Coupon>();
        }
    
        public long BranchId { get; set; }
        public string BranchTitle { get; set; }
        public string BranchAddressLine1 { get; set; }
        public string BranchAddressLine2 { get; set; }
        public string BranchCity { get; set; }
        public string BranchState { get; set; }
        public string BranchZipCode { get; set; }
        public string BranchPhone { get; set; }
        public string BranchLocationLat { get; set; }
        public string BranchLocationLong { get; set; }
        public Nullable<long> BranchCategoryId { get; set; }
        public Nullable<int> CompanyId { get; set; }

        public Nullable<int> CountryId { get; set; }

        public Nullable<bool> IsDefault { get; set; }
    
        public virtual BranchCategory BranchCategory { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}
