//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponRatingReview
    {
        public long CouponReviewId { get; set; }
        public Nullable<long> CouponId { get; set; }
        public Nullable<double> StarRating { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> RatingDateTime { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReviewImage1 { get; set; }
        public string ReviewImage2 { get; set; }
        public string Reviewimage3 { get; set; }
    
        public virtual Coupon Coupon { get; set; }
    }


    
}
