//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phrase
    {
        public int PhraseId { get; set; }
        public string PhraseName { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
