//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMD.Models.DomainModels{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class SharedSurveyQuestion
    {
       
    
        public long SSQID { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string SurveyTitle { get; set; }
        public string LeftPicturePath { get; set; }
        public string RightPicturePath { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }

        public long SharingGroupId { get; set; }

        public virtual ICollection<SurveySharingGroupShare> SurveySharingGroupShares { get; set; }


        public virtual SurveySharingGroup SurveySharingGroup { get; set; }

        [NotMapped]
        public string LeftPictureDataString { get; set; }
        [NotMapped]
        public string LeftPictureExtention { get; set; }
        [NotMapped]
        public string RightPictureDataString { get; set; }
        [NotMapped]
        public string RightPictureExtention { get; set; }
    }
}
