//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySharingGroup
    {
       
    
        public long SharingGroupId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string UserId { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual ICollection<SurveySharingGroupMember> SurveySharingGroupMembers { get; set; }


        public virtual ICollection<SharedSurveyQuestion> SharedSurveyQuestions { get; set; }

    }
}
