//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMD.Implementation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMD.Implementation.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No identity provider claim specified. Cannot proceed..
        /// </summary>
        internal static string ClaimsSecurityService_IdentityProviderClaim {
            get {
                return ResourceManager.GetString("ClaimsSecurityService_IdentityProviderClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name identifier claim specified. Cannot proceed..
        /// </summary>
        internal static string ClaimsSecurityService_MissingNameIdentifierClaim {
            get {
                return ResourceManager.GetString("ClaimsSecurityService_MissingNameIdentifierClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate Template pages from specified pdf..
        /// </summary>
        internal static string ItemService_FailedToGeneratePagesFromPdf {
            get {
                return ResourceManager.GetString("ItemService_FailedToGeneratePagesFromPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate pdf from specified template pages..
        /// </summary>
        internal static string ItemService_FailedToGeneratePdfFromPages {
            get {
                return ResourceManager.GetString("ItemService_FailedToGeneratePdfFromPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Path..
        /// </summary>
        internal static string ItemService_InvalidFilePath {
            get {
                return ResourceManager.GetString("ItemService_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product..
        /// </summary>
        internal static string ItemService_InvalidItem {
            get {
                return ResourceManager.GetString("ItemService_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with Id {0} not found..
        /// </summary>
        internal static string ItemService_ItemNotFound {
            get {
                return ResourceManager.GetString("ItemService_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code already exists..
        /// </summary>
        internal static string ItemService_ProductCodeDuplicated {
            get {
                return ResourceManager.GetString("ItemService_ProductCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete template..
        /// </summary>
        internal static string ItemService_TemplateDeleteFailed {
            get {
                return ResourceManager.GetString("ItemService_TemplateDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with Id {0} not found..
        /// </summary>
        internal static string ItemService_TemplateNotFound {
            get {
                return ResourceManager.GetString("ItemService_TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation with Id {0} not found..
        /// </summary>
        internal static string MyOrganisationService_OrganisationNotFound {
            get {
                return ResourceManager.GetString("MyOrganisationService_OrganisationNotFound", resourceCulture);
            }
        }
    }
}
