//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMD.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMD.Models.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Addon CostCenter is null..
        /// </summary>
        internal static string ItemAddonCostCentre_InvalidItem {
            get {
                return ResourceManager.GetString("ItemAddonCostCentre_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is null..
        /// </summary>
        internal static string ItemClone_InvalidItem {
            get {
                return ResourceManager.GetString("ItemClone_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Brief Answer is null..
        /// </summary>
        internal static string ItemClone_InvalidProductMarketBriefAnswer {
            get {
                return ResourceManager.GetString("ItemClone_InvalidProductMarketBriefAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Brief Question is null..
        /// </summary>
        internal static string ItemClone_InvalidProductMarketBriefQuestion {
            get {
                return ResourceManager.GetString("ItemClone_InvalidProductMarketBriefQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ItemVdpPrice must be specified..
        /// </summary>
        internal static string ItemMapper_CreateItemVdpPriceMustBeSpecified {
            get {
                return ResourceManager.GetString("ItemMapper_CreateItemVdpPriceMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ItemVdpPrice must be specified..
        /// </summary>
        internal static string ItemMapper_DeleteItemVdpPriceMustBeSpecified {
            get {
                return ResourceManager.GetString("ItemMapper_DeleteItemVdpPriceMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price Matrix is null..
        /// </summary>
        internal static string ItemPriceMatrixClone_InvalidItem {
            get {
                return ResourceManager.GetString("ItemPriceMatrixClone_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Product Detail is null..
        /// </summary>
        internal static string ItemProductDetailClone_InvalidItemProductDetail {
            get {
                return ResourceManager.GetString("ItemProductDetailClone_InvalidItemProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Section is null..
        /// </summary>
        internal static string ItemSectionClone_InvalidItemSection {
            get {
                return ResourceManager.GetString("ItemSectionClone_InvalidItemSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Ink Coverage is null..
        /// </summary>
        internal static string ItemSectionInkCoverageClone_InvalidInkCoverage {
            get {
                return ResourceManager.GetString("ItemSectionInkCoverageClone_InvalidInkCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item State Tax is null..
        /// </summary>
        internal static string ItemStateTaxClone_InvalidItem {
            get {
                return ResourceManager.GetString("ItemStateTaxClone_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Stock Option is null..
        /// </summary>
        internal static string ItemStockOption_InvalidItemStockOption {
            get {
                return ResourceManager.GetString("ItemStockOption_InvalidItemStockOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Vdp Price is null..
        /// </summary>
        internal static string ItemVdpPriceClone_InvalidItem {
            get {
                return ResourceManager.GetString("ItemVdpPriceClone_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category Item is null..
        /// </summary>
        internal static string ProductCategoryItemClone_InvalidItem {
            get {
                return ResourceManager.GetString("ProductCategoryItemClone_InvalidItem", resourceCulture);
            }
        }
    }
}
